### ISSUE TITLE
Slider tooltip?

### ISSUE THREAD

**Issue by lluiscab** [Wikiki/bulma-slider#1]
Would it be possible to add a tooltip to the slider like the one [here](https://wikiki.github.io/bulma-extensions/tooltip)?

Example (Ignore the animation, best gif I could find)
![Example](http://www.codebringer.com/wp-content/uploads/2017/07/1500461793_919_designing-the-perfect-slider.gif)

**Comment by Wikiki** [comment]
Done ;-)

I've added the style and the JS code to handle it.

Please look at the documentation to see it in action.

Regards

**Comment by imikim** [comment]
Adding .tooltip to the input with class .slider positions the tooltip in the middle of the slider - Is it possible to position it above the thumb?
