### ISSUE TITLE
Uncaught ReferenceError: outputs is not defined

### ISSUE THREAD

**Issue by frncsdrk** [Wikiki/bulma-slider#11]
The Error occurs because of the `use strict` statement in conjunction with the use of a global variable instead of a local variable.

See screenshot:  
![bulma-slider-error-screenshot](https://user-images.githubusercontent.com/19313266/36646060-aaf4bcfa-1a72-11e8-9830-cec7684b1aa4.png)

**Comment by enesaktay** [comment]
Pretty sure this can be closed
