### ISSUE TITLE
Runtime error: outputs is not defined

### ISSUE THREAD

**Issue by devth** [Wikiki/bulma-slider#16]
![jserror](https://user-images.githubusercontent.com/86107/37715926-e0eca660-2ce2-11e8-956e-ea0c94a9d49b.png)

Looks like this is preventing [the demo](https://wikiki.github.io/form/slider/) from working.

**Comment by devth** [comment]
Maybe an uglify issue? The [original source](https://cdn.jsdelivr.net/npm/bulma-slider@1.0.3/dist/bulma-slider.js) works fine.

**Comment by Wikiki** [comment]
Hi,

I just forgot to update the demo site.
Will be done soon.

Thank to notice.
