### ISSUE TITLE
Wrong slider picker position

### ISSUE THREAD

**Issue by koddr** [Wikiki/bulma-slider#2]
At macOS Sierra (10.12.6) and Safari (10.1.2) `bulma-slider`'s picker looks like:

![2017-09-13_13-37-46](https://user-images.githubusercontent.com/11155743/30373107-e17d01ae-9888-11e7-9ba6-e134b2a08648.png)

More `padding-top` for slider line, I think.
I see source code, but I don't found a solution to fix it.

**Comment by Wikiki** [comment]
Fixed by commit [d7152e86ab5b61e1c50ac378de0838bce31f9d90](https://github.com/Wikiki/bulma-slider/commit/d7152e86ab5b61e1c50ac378de0838bce31f9d90)

**Comment by koddr** [comment]
Thanks a lot!
