### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by Santiago8888** [Wikiki/bulma-slider#20]
[This package](https://www.jsdelivr.com/package/npm/bulma-slider) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by Wikiki** [comment]
Hi,

Look at https://github.com/Wikiki/bulma-slider/blob/master/package.json: there is a main and a style properties definition.
