### ISSUE TITLE
Uncaught Reference: isString is not defined

### ISSUE THREAD

**Issue by allannk** [Wikiki/bulma-slider#28]
I'm getting an error for the `isString` function, that I cannot seem to find anywhere. Did you forget to list some dependency? 

Happens at approx line 252 in the non-minified version.

```
Uncaught ReferenceError: isString is not defined
    at Function.value (bulma-slider.min.js:formatted:172)
    at (index):157
```

I've tried to replace it with a regular check for `type === "string"`, and altough the error disappear, there is no slider.

**Comment by marcuus** [comment]
I copied the utils folder from tagsinput/src and added `import * as utils from './utils/type';` to the top of index.js

**Comment by devblaze** [comment]
I have the same problem, I have searched for a couple of days and I think it's the laravel version the problem although I haven't tried to change version

**Comment by Wikiki** [comment]
Hi @devblaze ,

which version are you using ? Because `isString` function is declared on line 3 in th emain js file: https://github.com/Wikiki/bulma-slider/blob/master/src/js/index.js

**Comment by devblaze** [comment]
I am using Laravel version 7.2, my file didn't have that line I tried adding it
![image](https://user-images.githubusercontent.com/7489024/91166744-8150bd80-e6db-11ea-88a8-0909aa249c14.png)
and I got this after and when I remove the slider completely I still get the same error
![image](https://user-images.githubusercontent.com/7489024/91166847-a9402100-e6db-11ea-855d-690d1446b078.png)

Here is the blade:
![image](https://user-images.githubusercontent.com/7489024/91166899-bf4de180-e6db-11ea-8020-c27adc7e2c4b.png)

And the Vue component I made:
![image](https://user-images.githubusercontent.com/7489024/91166969-d68ccf00-e6db-11ea-8dbc-8e721824816f.png)
