### ISSUE TITLE
Vertical bar styling issues

### ISSUE THREAD

**Issue by octoshrimpy** [Wikiki/bulma-slider#3]
Looks like the vertical bar is not being properly styled in latest stable chrome.

https://puu.sh/xVGH3/715ca276a0.png

**Comment by Wikiki** [comment]
Hi @octoshrimpy ,

this is a Browser issue: https://bugs.chromium.org/p/chromium/issues/detail?id=341071
I'll try to user something else than <code>-webkit-appearance: slider-vertical</code> to display the vertical slider.

**Comment by machinaeXphilip** [comment]
on  Chromium 97.0.4692.99 I do get a warning now:

```console
The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
```

I wonder if that is related. In any case, it might become relevant soon.
