### ISSUE TITLE
Compile error: semicolons aren't allowed in the indented syntax

### ISSUE THREAD

**Issue by elhigu** [Wikiki/bulma-slider#41]
@import 'node_modules/bulma-extensions/bulma-slider/src/sass/index.sass';

```
Error: semicolons aren't allowed in the indented syntax.
   ╷
86 │                 vertical-align: middle;
   │                                       ^
   ╵
  node_modules/bulma-extensions/bulma-slider/src/sass/index.sass 86:27  root stylesheet
  src/styles/app.scss 3:9                                               root stylesheet
```

sass@1.19.0

**Comment by elhigu** [comment]
Seems to be fixed in master and `bulma-slider` npm package, so it seems that `bulma-extensions` is just out of date.

**Comment by AGINJITH** [comment]
make sure the file extension you have created is filename.scss not the file extension is not .sass it .scss. Thats how i got it right. thank you.

**Comment by dawnnguyen-vn** [comment]
> make sure the file extension you have created is filename.scss not the file extension is not .sass it .scss. Thats how i got it right. thank you.

Thanks
