### ISSUE TITLE
Bulma-slider.sass missing from dist 

### ISSUE THREAD

**Issue by 8BitAron** [Wikiki/bulma-slider#44]
I believe this change is at fault 

https://github.com/Wikiki/bulma-slider/commit/43cb21ae4a26795816229bd839babfb5c1eae497#r34936193

**Comment by Wikiki** [comment]
Hi,

Yes sass file has been removed from dist because it's the source file and it's then available within src directory.

regards

**Comment by FuuuuUuuuUUuuUUUuUUUU** [comment]
Hi,
this change break some projects. 
I have the 2.0.0 on my package.lock, but npm install dl the 2.0.4 (no more tag in 2.0.0, perhaps ? or I miss something)
And this change dist/css/bulma-slider.sass break the build.
