### ISSUE TITLE
Issue with vendor pseude selectors & unkown behavior

### ISSUE THREAD

**Issue by StaffOfHades** [Wikiki/bulma-slider#47]
I am using bulma & bulma extensions in a purely browser native environment (ie, no npm or similiar), serving static files. I have compiled the sass files for both bulma & bulma extensions into a single css file, which I also passed through autoprefixer.
When I attempt to use this css class & add a bulma-slider component, none of the pseudo classes are appearing.
I managed to narrow the issue according to this: [https://stackoverflow.com/questions/41246634/why-do-css-comma-separated-selectors-break-entire-rule-when-one-part-is-unknown](Why do css comma separated selectors break entire rule when one part is unknown?)
I confirmed this was the problem by having each vendor pseudo selector on its own, which when compiling to the appropriate css file fixed this issue.
I leave this here to other people can find the issue, but also to see if anything can be done.

**Comment by Wikiki** [comment]
Thanks for the notice. v2.0.2 now integrate each pseudo classes one by one.
