### ISSUE TITLE
Remove semi-colon!

### ISSUE THREAD

**Issue by hassanazimi** [Wikiki/bulma-slider#48]
Hi, this issue is being around for a long time.
I do not think we need semicolon on these lines after `vertical-align: middle`

THERE ARE 2 OF THEM.

https://github.com/Wikiki/bulma-slider/blob/4958d1ae27e84174731c80715c3ebf4ad5d1f5de/src/sass/index.sass#L85-L91

**Comment by hassanazimi** [comment]
Hello?

**Comment by Wikiki** [comment]
Source in master branch was already good. I forgot to update npm version. I'll do it today.
