### ISSUE TITLE
Documentation with broken JS

### ISSUE THREAD

**Issue by notJackson** [Wikiki/bulma-slider#5]
https://wikiki.github.io/bulma-extensions/slider#sliderJsExample

See PR https://github.com/Wikiki/bulma-slider/pull/4

**Comment by Wikiki** [comment]
Sorry, I revert your PR because the initial code was good. It's slider input which have has-output class. So the test is on the right variable (slider and not output)

Regards

**Comment by notJackson** [comment]
It is indeed good, I did also only spot it after you accepted my PR.
But the docs do not provide working JS code. 

![ewl6nwi](https://user-images.githubusercontent.com/16776447/32181395-8ae47e9a-bd94-11e7-9d1f-437ac8d57d0a.png)

**Comment by Wikiki** [comment]
You're right, thanks
