### ISSUE TITLE
module build failed

### ISSUE THREAD

**Issue by harpagon210** [Wikiki/bulma-slider#6]
Hi,

I have the following error when webpack tries to build my app:
```
$slider-radius: $radius !default
               ^
      Undefined variable: "$radius".
      in ....../node_modules/bulma-slider/slider.sass (line 1, column 17)
 @ ../node_modules/bulma-slider/slider.sass 4:14-92
```
Any idea of what is wrong?
Do I have to import another module?

**Comment by Wikiki** [comment]
Hi @harpagon210,

did you import Bulma first ?

rehgards

**Comment by harpagon210** [comment]
Hi thanks for your quick reply ;)

Yes, here is my imports:

```js
import 'bulma'
import 'bulma-slider'
```

thanks

**Comment by harpagon210** [comment]
@Wikiki there is no bulma-slider.sass in the node-modules/bulma-slider folder ;)

**Comment by Wikiki** [comment]
Weird.

Can you try with this:

```sass
@import 'bulma/sass/utilities/_all'
@import 'bulma-slider'
@import 'bulma'
```

**Comment by harpagon210** [comment]
I have the same error :(

**Comment by harpagon210** [comment]
I import via my javascript code, is that a problem? (I'm not used to webpack yet so I might be importing the files the wrong way...)

my js file:
```js
import 'bulma/sass/utilities/_all.sass'
import 'bulma-slider/slider.sass'
import 'bulma/css/bulma.css'
```

**Comment by Wikiki** [comment]
You need to create a sass file in which you import files:
```sass
@import 'bulma'
@import 'bulma-slider'
```

you can't import sass (or css) files into JS.

**Comment by harpagon210** [comment]
Thanks for your answer, what I did to fix the problem is that I created a sass file like you said.
I was supposed to be able to load css files through webpack in my js but nevermind, I have to learn more about webpack I guess as I'm probably doing something wrong...
