### ISSUE TITLE
Question: is it possible to restrict max value to less than slider max?

### ISSUE THREAD

**Issue by dvergeylen** [Wikiki/bulma-slider#7]
Hi @Wikiki ,

I have to say I am fond of your Bulma extensions!
Is it possible to have a slider with a maximum of (say) 100, but able to slide until 80?

My use case is a global budget that I have to split up in different posts. The sum of all sliders can't be bigger than the global budget (hence a max value of the slider different from the max value one can assign, depending on the other slider values).

Cheers from Belgium!

**Comment by Wikiki** [comment]
Hi,

this is not possible with default input range behavior.
Maybe adding some javascript plugged on change event will do the job.
